### ISSUE TITLE
ls command not found

### ISSUE THREAD

**Issue by harrylove** [rv-kip/express-redis-cache#47]
version 0.1.8

```
$ express-redis-cache ls
/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:14
    throw error;
    ^

TypeError: cache.ls is not a function
    at Domain.<anonymous> (/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:178:15)
    at Domain.run (domain.js:221:14)
    at /usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:17:10
    at Object.<anonymous> (/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:270:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
```

**Comment by asrashley** [comment]
Changing `cache.ls` to `cache.get` fixes that problem.
I also had to install moment

```
( cd node_modules/express-redis-cache/ && npm install moment)
```

**Comment by Maples7** [comment]
Did the commands really pass the tests?

**Comment by selfagency** [comment]
i'm using 1.0.0 and i just got this

```
daniel at selfagency-macpro in ~/Dev/nylon-web on dev [?]
❯ npm -g install express-redis-cache                                                                  12:17
/usr/local/bin/express-redis-cache -> /usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js
+ express-redis-cache@1.0.0
added 7 packages in 5.206s

daniel at selfagency-macpro in ~/Dev/nylon-web on dev [?]
❯ express-redis-cache ls                                                                          10s 274ms
/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:14
    throw error;
    ^

TypeError: cache.ls is not a function
    at Domain.<anonymous> (/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:178:15)
    at Domain.run (domain.js:317:14)
    at /usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:17:10
    at Object.<anonymous> (/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:270:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
```
