### ISSUE TITLE
size command callback is not a function

### ISSUE THREAD

**Issue by harrylove** [rv-kip/express-redis-cache#48]
version 0.1.8

```
$ express-redis-cache size
/usr/local/lib/node_modules/express-redis-cache/bin/express-redis-cache.js:14
    throw error;
    ^

TypeError: callback is not a function
    at Domain.<anonymous> (/usr/local/lib/node_modules/express-redis-cache/lib/ExpressRedisCache/size.js:21:5)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:65:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:119:16)
    at process._fatalException (node.js:229:33)
```

**Comment by kilik52** [comment]
i've got the same issue.

```
cache.size(function (err, numByte) {
        res.json({size: numByte})
});
```

gives me 

```
client.keys is not a function
```

error

**Comment by Maples7** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
#81

**Comment by krazyjakee** [comment]
Solved in v2 for now
