### ISSUE TITLE
TypeError: Cannot set property 'name' of null

### ISSUE THREAD

**Issue by lone112** [rv-kip/express-redis-cache#56]
TypeError: Cannot set property 'name' of null
    at Command.<anonymous> (/home/mdladmin/source/web-chat/JavaScript/node_modules/express-redis-cache/lib/ExpressRedisCache/get.js:45:27)
    at intercepted (domain.js:258:14)
    at Command.runIntercepted (domain.js:272:12)
    at bound (domain.js:287:14)
    at Command.runBound (domain.js:300:12)
    at RedisClient.return_reply (/home/mdladmin/source/web-chat/JavaScript/node_modules/express-redis-cache/node_modules/redis/index.js:664:25)

**Comment by magnusburton** [comment]
Just occurred for me as well.
