### ISSUE TITLE
Cannot set property 'name' of null

### ISSUE THREAD

**Issue by hrefcl** [rv-kip/express-redis-cache#68]
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot set property 'name' of null
    at Command.<anonymous> (/home/ec2-user/server/api/node_modules/express-redis-cache/lib/ExpressRedisCache/get.js:45:27)
    at Command.b (domain.js:177:20)
    at Command.b [as callback](domain.js:183:18)
    at normal_reply (/home/ec2-user/server/api/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/home/ec2-user/server/api/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/home/ec2-user/server/api/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/home/ec2-user/server/api/node_modules/redis/node_modules/redis-parser/lib/parser.js:413:12)
    at Socket.<anonymous> (/home/ec2-user/server/api/node_modules/redis/index.js:267:27)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

**Comment by edubart** [comment]
This error happens with me frequently too.

```
TypeError: Cannot set property 'name' of null
    at /opt/newsite/node_modules/express-redis-cache/lib/ExpressRedisCache/get.js:45:27
    at intercepted (domain.js:251:14)
    at runIntercepted (domain.js:265:12)
    at nrWrappedHandler (/opt/newsite/node_modules/newrelic/lib/transaction/tracer/index.js:386:19)
    at wrapped (/opt/newsite/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrappedCallback (/opt/newsite/node_modules/newrelic/lib/transaction/tracer/index.js:438:66)
    at wrapped (/opt/newsite/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at try_callback (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/index.js:321:14)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_reply (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/opt/newsite/node_modules/express-redis-cache/node_modules/redis/index.js:102:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
