### ISSUE TITLE
TypeError: Cannot assign to read only property 'callback' of keys

### ISSUE THREAD

**Issue by connexease** [rv-kip/express-redis-cache#73]
```
TypeError: Cannot assign to read only property 'callback' of keys
at RedisClient.internalSendCommandWrapper (/app/node_modules/newrelic/lib/instrumentation/redis.js:76:22)
at RedisClient.wrappedFunction [as internal_send_command] (/app/node_modules/newrelic/lib/transaction/tracer/index.js:366:24)
at RedisClient.(anonymous function).RedisClient.(anonymous function) (/app/node_modules/redis/lib/commands.js:45:25)
at Domain.<anonymous> (/app/node_modules/express-redis-cache/lib/ExpressRedisCache/get.js:36:19)
at Domain.run (domain.js:228:14)
at ExpressRedisCache.get (/app/node_modules/express-redis-cache/lib/ExpressRedisCache/get.js:25:12)
at expressRedisCache_Middleware (/app/node_modules/express-redis-cache/lib/ExpressRedisCache/route.js:158:14)
at Layer.handle (/app/node_modules/express/lib/router/layer.js:95:5)
at Layer.wrappedLayerHandleRequest [as handle_request] (/app/node_modules/newrelic/lib/instrumentation/express.js:428:32)
at next (/app/node_modules/express/lib/router/route.js:131:13)
at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
at dispatch (eval at wrapHandle (/app/node_modules/newrelic/lib/instrumentation/express.js:539:19), <anonymous>:12:19)
at Layer.handle (/app/node_modules/express/lib/router/layer.js:95:5)
at Layer.wrappedLayerHandleRequest [as handle_request] (/app/node_modules/newrelic/lib/instrumentation/express.js:428:32)
at /app/node_modules/express/lib/router/index.js:277:22
at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
```

**Comment by anonrig** [comment]
+1

**Comment by anonrig** [comment]
@rv-kip express-redis-cache uses redis version 2.4 that doesn't work with 2.6 on high traffic, and keeps getting us "request timeout".
